### ISSUE TITLE
[BUG]: No .env.example found ?

### ISSUE THREAD

**Issue by Piyush-linux** [allsimpledevcode/foodie-eats#1]
**Problem**
- `.env.example` was not found

**Solution**
- Create `.env.example` and insert the require variable

**Comment by withlakshmanan** [comment]
Hi @Piyush-linux,
  Yes it's ignore the .env variable in my local. for project setup and doubt refer this video tutorial [Link](https://www.youtube.com/watch?v=vS8UA8n6-ic)
